using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoCV.Contracts.Dtos
{
    public class CandidateProfileDto
    {
        public string ProfileId { get; set; } = "SAMPLE_ID";
        public string Header { get; set; } = "";            // keep as string for now
        public List<ExperienceDto> Experiences { get; set; } = new();
        public List<ProjectDto> Projects { get; set; } = new();
        public List<EducationDto> Educations { get; set; } = new();  // array
        public string FreeText { get; set; } = "<!-- Free text not specified. -->";        // additional free text info
        public string Signature {  get; set; }  = "Default signature: Generated by AutoCV"; // signature/footer
    }

}
