version: "3.9"

services:
  web:
    build:
      context: ../AutoCV.Web
    container_name: autocv-web
    ports:
      - "8080:8080"
    depends_on:
      - sql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql;Database=AutoCV;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    volumes:
      - ../data:/data

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: autocv-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
